Language.create([
  {name: "Ruby"},
  {name: "Rails"},
  {name: "SQL"},
  {name: "HTML"},
  {name: "CSS"},
  {name: "JavaScript"},
  {name: "jQuery"},
  {name: "json"},
  {name: "AJAX"},
  {name: "AngularJS"},
  {name: "EmberJS"},
  {name: "BackboneJS"},
  {name: "PHP"},
  {name: "WordPress"},
  {name: ".Net"},
  {name: "Python"},
  {name: "Java"},
  {name: "C"},
  {name: "C++"},
  {name: "C#"}, 
])